openapi: "3.1.0"
info:
  title: Online Order API
  version: 1.0.0
  description: >
    A basic API for managing user groups, records, user registration, and LINE login.

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

paths:
  /mrsaccountant/user/groups:
    get:
      summary: Retrieve all groups for the authenticated user
      description: Fetches all groups associated with the authenticated user.
      operationId: getUserGroups
      responses:
        "200":
          description: A list of user groups.
          content:
            application/json:
              examples:
                userAllGroups:
                  summary: Sample response
                  value:
                    - groupName: Marketing Team
                      createdAt: "2024-11-21"
                      groupTransactions: []
                      groupId: 2
                    - groupName: Test Group
                      createdAt: "2024-11-21"
                      groupTransactions: []
                      groupId: 6
        "204":
          description: No groups found for the user.
        default:
          description: An error occurred while retrieving user groups.
      tags:
        - User Groups
    post:
      summary: Create a new group for the authenticated user
      description: Adds a new group to the authenticated user's account.
      operationId: createUserGroup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                groupName:
                  type: string
                  description: The name of the new group.
              required:
                - groupName
      responses:
        "201":
          description: Group created successfully.
          content:
            application/json:
              schema:
                type: string
                example: Group added successfully!
        "400":
          description: Invalid group data provided.
        default:
          description: An error occurred while creating the group.
      tags:
        - User Groups

  /group/user/{userId}/{groupId}:
    post:
      summary: Add a user to a group
      description: Adds a user to a specific group by their IDs.
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user to be added to the group
          schema:
            type: integer
        - name: groupId
          in: path
          required: true
          description: ID of the group to which the user will be added
          schema:
            type: integer
      responses:
        "200":
          description: User successfully added to the group
          content:
            application/json:
              schema:
                type: string
                example: "User successfully added to the group."
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: string
                example: "Invalid input data"
        "404":
          description: User or Group not found
          content:
            application/json:
              schema:
                type: string
                examples:
                  UserNotFound:
                    summary: User not found
                    value: "User not found with ID: {userId}"
                  GroupNotFound:
                    summary: Group not found
                    value: "Group not found with ID: {groupId}"
        "500":
          description: Unexpected error
          content:
            application/json:
              schema:
                type: string
                example: "An unexpected error occurred."
      tags:
        - User Management

  /mrsaccountant/group/transaction:
    get:
      summary: Retrieve all transactions by group ID
      description: Fetches all group transactions associated with the specified group ID.
      parameters:
        - name: groupId
          in: query
          required: true
          description: The ID of the group to retrieve transactions for
          schema:
            type: integer
      responses:
        "200":
          description: A list of group transactions
          content:
            application/json:
              examples:
                sampleResponse:
                  summary: Sample response
                  value:
                    - transactionId: 1
                      name: Dinner with friends
                      amount: 1500.0
                      date: "2024-12-05"
                      category: Food
                      type: EXPENSE
                      transactionSplits:
                        - userId: 1
                          amount: 750.0
                          role: PAYER
                        - userId: 2
                          amount: 750.0
                          role: RECEIVER
        "404":
          description: No transactions found for the group.
        "500":
          description: An error occurred while retrieving transactions.
      tags:
        - Transactions

  /mrsaccountant/group/transaction/{groupId}:
    post:
      summary: Create a new group transaction
      description: Creates a transaction for the specified group with transaction splits.
      parameters:
        - name: groupId
          in: path
          required: true
          description: The ID of the group for which the transaction is being created
          schema:
            type: integer
      requestBody:
        required: true
        description: Details of the group transaction to be created
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  description: Total amount of the transaction
                type:
                  type: string
                  description: Type of the transaction (e.g., EXPENSE, INCOME, TRANSFER)
                category:
                  type: string
                  description: Category of the transaction (e.g., Food, Travel)
                date:
                  type: string
                  format: date
                  description: Date of the transaction in YYYY-MM-DD format
                name:
                  type: string
                  description: Name or description of the transaction
                transactionSplits:
                  type: array
                  description: List of transaction splits associated with the group transaction
                  items:
                    type: object
                    properties:
                      userId:
                        type: integer
                        description: ID of the user associated with the split
                      amount:
                        type: number
                        description: Amount allocated to the user
                      role:
                        type: string
                        description: Role of the user in the transaction (e.g., PAYER, RECEIVER)
      responses:
        "200":
          description: GroupTransaction created successfully
        "400":
          description: Invalid data provided
        "404":
          description: Group not found
        "500":
          description: Internal server error
      tags:
        - Transactions

  /mrsaccountant/group/transaction/{transactionId}:
    put:
      summary: Update an existing group transaction
      description: Updates details of a specified group transaction by transaction ID.
      parameters:
        - name: transactionId
          in: path
          required: true
          description: The ID of the transaction to update
          schema:
            type: integer
      requestBody:
        required: true
        description: Updated details of the group transaction
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  description: Updated total amount of the transaction
                type:
                  type: string
                  description: Updated type of the transaction
                category:
                  type: string
                  description: Updated category of the transaction
                date:
                  type: string
                  format: date
                  description: Updated date of the transaction
                name:
                  type: string
                  description: Updated name or description of the transaction
                transactionSplits:
                  type: array
                  description: Updated transaction splits
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: ID of the transaction split to update
                      userId:
                        type: integer
                        description: ID of the user associated with the split
                      amount:
                        type: number
                        description: Amount allocated to the user
                      role:
                        type: string
                        description: Role of the user in the transaction
      responses:
        "200":
          description: GroupTransaction updated successfully
        "400":
          description: Invalid data provided
        "404":
          description: Transaction not found
        "500":
          description: Internal server error
      tags:
        - Transactions

    delete:
      summary: Delete a group transaction
      description: Deletes a specified group transaction by transaction ID.
      parameters:
        - name: transactionId
          in: path
          required: true
          description: The ID of the transaction to delete
          schema:
            type: integer
      responses:
        "200":
          description: GroupTransaction deleted successfully
        "404":
          description: Transaction not found
        "500":
          description: Internal server error
      tags:
        - Transactions

      /mrsaccountant/user/records:
    get:
      summary: Retrieve user records
      description: Fetches all records for the authenticated user, optionally filtered by date range.
      parameters:
        - name: startdate
          in: query
          required: false
          description: The start date for filtering records (inclusive).
          schema:
            type: string
            format: date
        - name: enddate
          in: query
          required: false
          description: The end date for filtering records (inclusive).
          schema:
            type: string
            format: date
      responses:
        "200":
          description: A list of user records.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The ID of the record.
                    name:
                      type: string
                      description: The name or description of the record.
                    amount:
                      type: number
                      description: The amount of the record.
                    date:
                      type: string
                      format: date
                      description: The date of the record.
                    category:
                      type: string
                      description: The category of the record.
                    type:
                      type: string
                      description: The type of the record (e.g., EXPENSE, INCOME).
        "400":
          description: Invalid date range provided.
        "500":
          description: An error occurred while retrieving records.
      tags:
        - Records

    post:
      summary: Add a new record
      description: Adds a new record for the authenticated user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name or description of the record.
                amount:
                  type: number
                  description: The amount of the record.
                date:
                  type: string
                  format: date
                  description: The date of the record.
                category:
                  type: string
                  description: The category of the record.
                type:
                  type: string
                  description: The type of the record (e.g., EXPENSE, INCOME).
      responses:
        "201":
          description: Record created successfully.
        "400":
          description: Invalid data provided.
        "500":
          description: An error occurred while creating the record.
      tags:
        - Records

  /mrsaccountant/user/records/{id}:
    put:
      summary: Update a user record
      description: Updates the details of a specified user record by ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the record to update.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The updated name or description of the record.
                amount:
                  type: number
                  description: The updated amount of the record.
                date:
                  type: string
                  format: date
                  description: The updated date of the record.
                category:
                  type: string
                  description: The updated category of the record.
                type:
                  type: string
                  description: The updated type of the record (e.g., EXPENSE, INCOME).
      responses:
        "200":
          description: Record updated successfully.
        "400":
          description: Invalid data provided.
        "404":
          description: Record not found.
        "500":
          description: An error occurred while updating the record.
      tags:
        - Records

    delete:
      summary: Delete a user record
      description: Deletes a specified user record by ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the record to delete.
          schema:
            type: integer
      responses:
        "202":
          description: Record deleted successfully.
        "404":
          description: Record not found.
        "500":
          description: An error occurred while deleting the record.
      tags:
        - Records
    /mrsaccountant/settlement/{groupId}:
    get:
      summary: Retrieve settlement details for a group
      description: Fetches the latest settlements and settlement statuses for the specified group ID.
      parameters:
        - name: groupId
          in: path
          required: true
          description: The ID of the group for which settlements are being retrieved.
          schema:
            type: integer
      responses:
        "200":
          description: Settlement details retrieved successfully.
          content:
            application/json:
              examples:
                settlementResponse:
                  summary: Example response
                  value:
                    settlementStatuses:
                      - payer: User1
                        receiver: User2
                        amount: 50.0
                      - payer: User3
                        receiver: User1
                        amount: 30.0
                    latestSettlements:
                      - user: User1
                        payAmount: 100.0
                        receiveAmount: 50.0
                        balanceAmount: 50.0
                      - user: User2
                        payAmount: 0.0
                        receiveAmount: 50.0
                        balanceAmount: -50.0
        "404":
          description: Group not found.
        "500":
          description: An error occurred while retrieving settlement details.
      tags:
        - Settlements
